trigger:
- main



stages:
  - stage: BuidStage
    jobs:
    - deployment: DeployWeb
      displayName: Deploy to web
    - job: BuildJob
      pool:
        vmImage: ubuntu-latest
        
      variables:
        buildConfiguration: 'Release'

      steps:
      - task: DotNetCoreCLI@2
        displayName: 'Restore the Build'
        inputs:
          command: 'restore'
          projects: '**/*.csproj'
      - task: DotNetCoreCLI@2
        displayName: 'Build'
        inputs:
          command: 'build'
          projects: '**/*.csproj'
          arguments: '--configuration $(buildConfiguration)'
      - task: DotNetCoreCLI@2
        displayName: 'Publish'
        inputs:
          command: 'publish'
          publishWebProjects: true
          arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'

  - stage: deploy
      dependsOn:BuidStage
    jobs:
    - deployment: DeployWeb
      displayName: Deploy to web
    - job: DevDeploy
      pool:
        vmImage: ubuntu-latest
      steps:
        - download: current
          artifact: drop




